### ISSUE TITLE
Indention

### ISSUE THREAD

**Issue by KevinSjoberg** [bufferapp/buffer-php-style-guide#1]
I'm used to working with spaces, others are used to working with tabs. I'd suggest an indention of 4 spaces for working with the PHP code. Spaces are always interpreted the same way while tabs can be displayed in a lot of different ways depending on where you view the code.

A few "standards" that also prefer spaces over tabs are:
- http://www.php-fig.org/psr/psr-2/
- http://pear.php.net/manual/en/standards.indenting.php

I do understand that most of the codebase currently is written with tabs and if we are to convert to spaces I'd suggest to do this gradually by converting files that you come across while working with the codebase.

I would love some input from everyone on this. :smile: What do you think?

**Comment by armab** [comment]
@sunils34 Why you guys don't just work with [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) coding style by [PHP-FIG community](http://www.php-fig.org/) which was mentioned here and became standard for the big amount of the Open Source PHP projects nowadays?

It's also easier to use it with [PHP Code Sniffer](https://github.com/squizlabs/PHP_CodeSniffer), which has predefined PSR-2 rules, so these coding style checks could be included inside your Continuous Integration process, to have fully automated way of following code style consistency without reinventing own bicycle.

**Comment by potherca** [comment]
Just a random idea, but if you guys still want to convert tabs to spaces (or vice-versa) without altering a file's  history in git, there are ways to achieve this "en masse".

As far as I can see, the options are:

- use git amend to alter the original commit (keeping the date and author intact but altering the content)
- using `git commit` with `--author` and `--date` flags  (so each white-space fix could be back-dated to match the original commit, keeping the history "sort of" real)

All of these would require a scripted solution, but that's what we developers do, right? :-)

Something like this could be fun to script and would also be (very?) useful for other projects looking to migrate to different styles (not just whitespace) without losing git history.

**Comment by hovsater** [comment]
Doing some issue cleanup on my side. I assume you've settled on something that works for you all. Cheers! 🙂
